#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  adEat:

services:

  node-app:
    container_name: adEat
    image: lotto/nodejs:v1.0.0
    restart: always
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_adEat

    working_dir: /usr/src/app
    command: npm start

    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    networks:
      - adEat
